# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b27cba79a27bb1f9dccbf854671c5cd938aa6aa5bf177853f87fda3c3fef23ea29837a555a38f95fec60cdaa042a1c73ecdaa3e8d156f41c77d12f8dc7df1c4

test:
  secret_key_base: fbb7ddd49d2b390dbc0db69025fa8261b647c644e62620965a8b54a9675a420e9b2b6a4529d58dc1a23dc2fa232552030b1949c17b4dc00c585c13116c82bc4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
